Allow downloads to fail for in-progress builds

diff --git a/bin/in b/bin/in
--- a/bin/in
+++ b/bin/in
@@ -16,9 +16,16 @@ version=$(jq -r .version.version < params)
 
 copr-cli get-package $project --name $package --with-all-builds > package.json
 build_id=$(jq ".builds | map(select(.pkg_version==\"$version\"))[0].id" < package.json)
+state=$(jq ".builds | map(select(.pkg_version==\"$version\"))[0].state" < package.json)
 if [ $build_id = "null" ]; then
     echo "Version $version not found" >&2
     exit 1
 fi
-copr download-build $build_id
+if [ $state = 'succeeded' ]; then
+    copr download-build $build_id
+else
+    # If the build hasn't run yet, then too bad if the download fails. This
+    # happens in the get-after-put, but never for downloads triggered by check
+    copr download-build $build_id || true
+fi
 jq -r '{"version": .version, "metadata": []}' < params >&3
